import { Project } from "./project.model";

export const projects: readonly Project[] = [
  {
    slug: "bunkerweb-waf",
    cardTitle: "BunkerWeb WAF",
    title: "Protección de WordPress con BunkerWeb WAF",
    category: "Cybersecurity",
    type: "Laboratorio académico de ciberseguridad",
    status: "Completed — documentation being refined",
    summary:
      "Despliegue académico de un Web Application Firewall con BunkerWeb para proteger una instalación de WordPress ejecutada sobre Ubuntu Server y Docker.",
    objective:
      "Desplegar y estudiar BunkerWeb como WAF y reverse proxy delante de una aplicación WordPress, y preparar un entorno en el que validar controles frente a tráfico web potencialmente malicioso.",
    technologies: [
      "Ubuntu Server",
      "BunkerWeb 1.5.x",
      "BunkerWeb UI",
      "WordPress 6.4",
      "PHP 8.2",
      "Apache",
      "MariaDB 10.11",
      "Docker",
      "Docker Compose",
      "Redes Docker",
      "Volúmenes Docker",
      "Reverse proxy",
      "ModSecurity / capacidades WAF de BunkerWeb",
    ],
    architecture: [
      "Cliente",
      "BunkerWeb WAF / reverse proxy",
      "WordPress",
      "MariaDB",
    ],
    architectureDescription:
      "El laboratorio se ejecutó sobre Ubuntu Server. Los servicios se desplegaron con Docker Compose, utilizando redes Docker para su comunicación y volúmenes para conservar los datos necesarios.",
    workPerformed: [
      "Preparación del servidor Ubuntu.",
      "Instalación y uso de Docker y Docker Compose.",
      "Definición del despliegue de BunkerWeb, WordPress y MariaDB.",
      "Configuración de redes y volúmenes Docker.",
      "Configuración del encaminamiento mediante reverse proxy.",
      "Configuración de la protección WAF delante de WordPress.",
      "Diagnóstico de problemas del despliegue.",
    ],
    confirmedResults: [
      "Se preparó el servidor Ubuntu para el laboratorio.",
      "Se definió un despliegue con BunkerWeb, WordPress y MariaDB.",
      "Se trabajó con redes y volúmenes Docker.",
      "BunkerWeb se situó como reverse proxy y capa WAF delante de WordPress.",
      "Se diagnosticaron problemas de configuración y estado de los servicios durante distintas iteraciones.",
    ],
    problems: [
      {
        title: "Estado de BunkerWeb UI",
        description:
          "Durante una iteración, BunkerWeb UI apareció como unhealthy y entró en un ciclo de reinicios. La causa y la solución definitiva siguen pendientes de documentar.",
      },
      {
        title: "Configuración de Docker Compose",
        description:
          "Algunas modificaciones introdujeron problemas en la estructura YAML de Docker Compose. No se atribuye todavía una causa concreta más allá de la configuración observada.",
      },
    ],
    documentationStatus: [
      "Se está revisando la documentación original para confirmar qué pruebas de SQL injection, XSS, path traversal y ataques relacionados con WordPress llegaron a ejecutarse.",
      "No se atribuyen bloqueos exitosos, tasas de detección ni vulnerabilidades explotadas hasta completar esa revisión.",
      "Las capturas y los diagramas se incorporarán únicamente después de ser revisados y sanitizados.",
    ],
  },
  {
    slug: "soc-snort-elk",
    cardTitle: "SOC / Snort / ELK",
    title: "Mini-SOC con Snort y Elastic/Kibana",
    category: "Cybersecurity",
    type: "Laboratorio académico de Blue Team y monitorización",
    status: "Completed — documentation being refined",
    summary:
      "Laboratorio académico orientado a centralizar eventos de red, IDS y servidor para su consulta y análisis con Snort y Elastic/Kibana.",
    objective:
      "Construir un entorno de monitorización y detección en el que los eventos de red y del servidor pudieran centralizarse para facilitar su consulta, análisis y correlación.",
    technologies: [
      "GNS3",
      "Ubuntu Server",
      "Snort",
      "Apache",
      "MySQL",
      "PHP",
      "WordPress",
      "iptables",
      "Elastic / ELK",
      "Elastic Cloud",
      "Kibana",
    ],
    architecture: [
      "Cliente",
      "Red de laboratorio GNS3",
      "Snort IDS",
      "Ubuntu Server",
      "Elastic Cloud / Elastic Stack",
      "Kibana",
    ],
    architectureDescription:
      "El servidor Ubuntu incluía Apache, MySQL, PHP, WordPress e iptables. Los eventos y registros se enviaban hacia Elastic para su consulta y análisis mediante Kibana.",
    workPerformed: [
      "Construcción de una topología de laboratorio en GNS3 con un cliente, Snort IDS y un servidor Ubuntu.",
      "Trabajo con servicios web, base de datos, aplicación y firewall en el servidor.",
      "Envío de eventos y registros hacia Elastic Cloud / Elastic Stack.",
      "Consulta y análisis de la información mediante Kibana.",
      "Trabajo conceptual con información de red, IDS, firewall y aplicación.",
    ],
    confirmedResults: [
      "Se construyó la arquitectura del mini-SOC.",
      "Se utilizó Snort como IDS dentro de la topología.",
      "Se trabajó con registros procedentes de diferentes capas del entorno.",
      "Los eventos y logs se enviaban hacia Elastic para su consulta y análisis con Kibana.",
    ],
    lessons: [
      "Centralización de eventos procedentes de distintas fuentes.",
      "Relación entre monitorización de red, IDS y registros del servidor.",
      "Consulta y correlación de información en Elastic/Kibana.",
    ],
    documentationStatus: [
      "Se está revisando la documentación antes de publicar reglas específicas, dashboards concretos o detecciones exitosas determinadas.",
      "Escaneos, peticiones web sospechosas y eventos de IDS, firewall y aplicación se presentan como ámbitos conceptuales, no como detecciones confirmadas.",
      "Las capturas y los diagramas se incorporarán únicamente después de ser revisados y sanitizados.",
    ],
  },
  {
    slug: "mobile-security-mobsf-mstg",
    cardTitle: "Mobile Security con MobSF / MSTG",
    title: "Análisis de InsecureBankv2 con MobSF y OWASP MSTG",
    category: "Cybersecurity",
    type: "Laboratorio académico de seguridad móvil",
    status: "Completed — documentation being refined",
    summary:
      "Análisis académico de la aplicación Android InsecureBankv2 mediante MobSF y una estructura de trabajo basada en OWASP MSTG.",
    objective:
      "Trabajar con distintas categorías de OWASP MSTG sobre aplicaciones móviles. La práctica contemplaba pruebas para Android e iOS, con pruebas dinámicas previstas únicamente para Android.",
    technologies: [
      "InsecureBankv2.apk",
      "Kali Linux 2025.2",
      "VirtualBox",
      "Android Emulator",
      "Android 11 / API 30",
      "Google APIs x86_64",
      "ADB",
      "MobSF",
      "OWASP MSTG",
    ],
    workPerformed: [
      "Carga de InsecureBankv2 en MobSF mediante Upload & Analyze.",
      "Ejecución de un análisis estático automatizado.",
      "Revisión de las observaciones generadas por MobSF sobre el paquete Android.",
    ],
    confirmedResults: [
      "MobSF mostró 4 de 10 activities como exportadas.",
      "MobSF mostró 1 de 2 receivers como exportado.",
      "MobSF mostró 1 de 1 provider como exportado.",
      "MobSF indicó que la aplicación utilizaba firma APK v1.",
      "MobSF indicó la ausencia de firma APK v2, v3 y v4.",
    ],
    documentationStatus: [
      "Los resultados confirmados son observaciones del informe automático de MobSF; no equivalen a vulnerabilidades explotadas o verificadas manualmente.",
      "Se está revisando qué comprobaciones manuales llegaron a realizarse.",
      "También está pendiente confirmar qué pruebas dinámicas y qué categorías concretas de OWASP MSTG se completaron.",
      "Las capturas y los informes se incorporarán únicamente después de ser revisados y sanitizados.",
    ],
  },
  {
    slug: "secure-portfolio-infrastructure",
    cardTitle: "Secure Portfolio Infrastructure",
    title: "Secure Portfolio Infrastructure",
    category: "DevOps",
    type: "Proyecto personal",
    status: "En curso",
    summary:
      "Proyecto personal para convertir este portfolio en una demostración progresiva de desarrollo Full Stack, automatización, infraestructura y ciberseguridad.",
    objective:
      "Construir algo más que una página de presentación: una plataforma que permita mostrar el proceso completo de desarrollo, backend, persistencia, contenerización, CI/CD, seguridad, orquestación, monitorización, detección y respuesta.",
    technologies: [
      "Angular 22",
      "TypeScript",
      "SCSS",
      "Angular Router",
      "SSR / prerendering",
      "NestJS 12",
      "REST API",
    ],
    architecture: [
      "Frontend Angular",
      "Contenido profesional",
      "Backend NestJS",
      "Persistencia",
      "Entrega y seguridad",
      "Orquestación y protección",
      "Monitorización, detección y respuesta",
    ],
    architectureDescription:
      "Frontend, contenido y API NestJS están implementados. Persistencia y los pasos posteriores representan el roadmap y todavía no forman parte de la plataforma.",
    repository: "https://github.com/alejandropena25-beep/cyber-portfolio",
    roadmap: {
      implemented: [
        "Angular 22",
        "TypeScript",
        "SCSS",
        "Angular Router",
        "Componentes standalone",
        "SSR / prerendering",
        "Diseño responsive",
        "Home",
        "Projects",
        "Project Detail",
        "About",
        "Contact",
        "Página 404",
        "Contenido profesional servido por la API",
        "Tests",
        "Build funcional",
        "Git",
        "GitHub",
        "Phase 2 — Portfolio Content",
        "NestJS 12",
        "API REST pública",
        "Endpoints de health, projects y profile",
        "Integración de Angular con la API",
        "Datos públicos tipados en memoria en el backend",
      ],
      inProgress: [
        "Phase 3 — NestJS Backend",
        "Documentación de la arquitectura frontend / API",
        "Revisión de material publicable",
      ],
      planned: [
        "PostgreSQL",
        "Administración / autenticación",
        "Docker / Docker Compose",
        "GitHub Actions",
        "DevSecOps y análisis de seguridad",
        "Kubernetes",
        "WAF / protección perimetral",
        "Wazuh SIEM",
        "Prometheus / Grafana",
        "Detección de incidentes",
        "Respuesta defensiva automatizada y controlada",
        "Despliegue final en producción",
      ],
    },
    documentationStatus: [
      "Las tecnologías del roadmap solo se incorporarán a la sección Implementado cuando formen parte verificable del proyecto.",
    ],
  },
];
